module.exports = {
    menuDashboardFlag:false,
    menuDispatchboardFlag:false,
    menuCustomerFlag:false,
    menuEstimatesFlag:false,
    menuWorkOrderFlag:false,
    menuInvoiceFlag:false,
    menuPaymentFlag:false,
    menuFollowupFlag:false,
    menuInventoryFlag:false,
    menuReportsFlag:false,
    menuStaffFlag:false,
    menuCommissionsFlag:false,
    menuPricebookFlag:false,
    menuAccountSettingsFlag:false,
    menuGlobalsettingsFlag:false,
    menuProfilesFlag:false,
    menuLeadsFlag:false,
    menuSubscriptionFlag:false,
    menuMarketingFlag:false,
    menuVendorsFlag:false,
    menuEquipmentFlag:false,
    menuAccountFlag:false,
    menuCardsFlag:false,
    menuFleetFlag:false,
    menuTwilioFlag:false,
    menuDispatchboardFlag: false
}